github:
  user: "Jenkins Infra Bot (updatecli)"
  email: "60776566+jenkins-infra-bot[bot]@users.noreply.github.com"
  username: "jenkins-infra-bot"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  owner: "jenkins-infra"
  repository: "docker-builder"
